[versions]
kotlin = "2.2.21"
jni = "1.1.0"
agp = "8.10.1"
filepicker = "0.12.0"
publish = "0.35.0"

[plugins]
mp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
knee = { id = "io.deepmedia.tools.knee", version = "1.2.0" }
android-lib = { id = "com.android.library", version.ref = "agp" }
android-app = { id = "com.android.application", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.21-2.0.4" }
compose-kt = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version = "1.9.3" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version = "0.29.0" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }

[libraries]
jni = { module = "dev.datlag.nkommons:jni", version.ref = "jni" }
jni-ksp = { module = "dev.datlag.nkommons:ksp", version.ref = "jni" }
jni-annotations = { module = "dev.datlag.nkommons:annotations", version.ref = "jni" }
io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.8.0" }

# For zero-copy bitmap on desktop.
skiko = { module = "org.jetbrains.skiko:skiko-awt", version = "0.9.22.2" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.10.2" }